# Generated by Django 3.0.4 on 2020-04-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(max_length=200)),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_address', models.CharField(max_length=200)),
                ('requester_nid', models.CharField(max_length=200)),
                ('requester_contact_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('request_reason', models.CharField(max_length=500)),
                ('creation_date', models.DateField(auto_now=True)),
                ('permit_signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dig_permit.Signers')),
            ],
        ),
    ]
