# Generated by Django 3.0.4 on 2020-04-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig_permit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
