# Generated by Django 3.0.4 on 2020-04-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig_permit', '0002_auto_20200408_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='request_reason',
            field=models.CharField(choices=[('NET', 'INTERNET'), ('CURRENT', 'CURRENT'), ('TV', 'TV'), ('OTHER', 'OTHER')], default='CURRENT', max_length=10),
        ),
    ]
