# Generated by Django 3.0.4 on 2020-04-09 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig_permit', '0003_auto_20200409_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='requester_date',
            field=models.DateField(default=datetime.date(2020, 4, 9)),
        ),
    ]
