# Generated by Django 3.0.4 on 2020-04-09 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dig_permit', '0004_permit_requester_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='requester_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
