# Generated by Django 3.0.4 on 2020-04-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig_permit', '0005_auto_20200409_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='requester_location',
            field=models.CharField(default='migen egeah ', max_length=500),
            preserve_default=False,
        ),
    ]
