# Generated by Django 3.1.3 on 2021-01-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dig_permit', '0006_permit_requester_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('pending', 'PENDING'), ('rejected', 'REJECTED')], default='pending', max_length=10),
        ),
    ]
